on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on:
      - self-hosted
    steps:
      - uses: google-github-actions/release-please-action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
          changelog-types: '[
            {"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"chore","section":"Miscellaneous","hidden":false},
            {"type":"dep","section":"Dependencies","hidden":false}
          ]'
